// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byjograuihjhlbdlxcdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5am9ncmF1aWhqaGxiZGx4Y2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODIyODEsImV4cCI6MjA2NzY1ODI4MX0.g61D-LFJnI27p5Q7X7hD8LtXUVcQDwGHdT_z0G2n_ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});